### ISSUE TITLE
PM2 fails when building quickstart on localhost. 

### ISSUE THREAD

**Issue by cgcardona** [TRON-US/docker-tron-quickstart#9]
Hi, Thanks for all the great work. Everything works great when I pull the quickstart from docker hub. 

However when I clone the `docker-tron-quickstart` repo to my localhost and then run `./bin/build` it complains about not having the large files in `conf/`

* FullNode.jar
* BlockParser.jar
* eventron

```
Whoops... Your repo is not ready.
Most likely you didn't pull a couple of large files.
To do it, install git-lfs:

    git lfs install

and pull the large files:

   git lfs pull
```

But running `git lfs pull` doesn't work

```
git lfs pull
[bbaebc4b3576e9057614d0d5b1580b5231993c908ecc7347196de83d9dc252e3] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/TRON-US/docker-tron-quickstart.git/info/lfs'
```

As a solution I was able to go back through the git history of the quickstart repo and find when the large files where checked in to github and I've been able to to get a copy of them that way. 

Now when I build and run the quickstart locally everything appears to work properly but the logs suggest that pm2 and eventron aren't running properly

```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications eventron not running, starting...
[PM2][ERROR] Process failed to launch Process could not be forked properly, check your system health
┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
```

Where can I find the files which make up these executables from the `conf/` directory?

* FullNode.jar
* BlockParser.jar
* eventron

Thanks!

**Comment by sullof** [comment]
The files for Quickstart are compiled for it. The right to use are in this repo. If you remove git-lfs and install it again correctly, it should work. If not, anyway, this is a git-lfs issue, not a Quickstart issue.

**Comment by cgcardona** [comment]
@sullof Which files are you using to compile for the quickstart? Are they open source?
